import 'dotenv/config';
import Database from 'better-sqlite3';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {
  ActionRowBuilder, ButtonBuilder, ButtonStyle, Client, EmbedBuilder, GatewayIntentBits,
  ModalBuilder, REST, Routes, SlashCommandBuilder, StringSelectMenuBuilder,
  TextInputBuilder, TextInputStyle,
  type ButtonInteraction, type ChatInputCommandInteraction, type Interaction,
  type ModalSubmitInteraction, type StringSelectMenuInteraction,
} from 'discord.js';

const token = process.env.DISCORD_TOKEN, clientId = process.env.CLIENT_ID, guildId = process.env.GUILD_ID;
if (!token || !clientId || !guildId) throw new Error('Missing DISCORD_TOKEN, CLIENT_ID or GUILD_ID in .env');
const dbPath = process.env.DATABASE_PATH || './data/tgs-tracker.db';
fs.mkdirSync(path.dirname(dbPath), {recursive:true});
const db = new Database(dbPath); db.pragma('journal_mode = WAL'); db.pragma('foreign_keys = ON');

db.exec(`
CREATE TABLE IF NOT EXISTS games(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE COLLATE NOCASE,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tournaments(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE COLLATE NOCASE,game_id INTEGER,password_hash TEXT,password_salt TEXT,status TEXT NOT NULL DEFAULT 'draft',created_by TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(game_id) REFERENCES games(id));
CREATE TABLE IF NOT EXISTS players(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE COLLATE NOCASE,discord_id TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tournament_players(tournament_id INTEGER NOT NULL,player_id INTEGER NOT NULL,seed INTEGER,joined_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(tournament_id,player_id),FOREIGN KEY(tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE,FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS races(id INTEGER PRIMARY KEY AUTOINCREMENT,tournament_id INTEGER NOT NULL,race_no INTEGER NOT NULL,track TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(tournament_id,race_no),FOREIGN KEY(tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS results(id INTEGER PRIMARY KEY AUTOINCREMENT,race_id INTEGER NOT NULL,player_id INTEGER NOT NULL,points REAL NOT NULL DEFAULT 0,position INTEGER,kd REAL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(race_id) REFERENCES races(id) ON DELETE CASCADE,FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE,UNIQUE(race_id,player_id));
CREATE TABLE IF NOT EXISTS matches(id INTEGER PRIMARY KEY AUTOINCREMENT,tournament_id INTEGER NOT NULL,round_name TEXT NOT NULL,match_no INTEGER NOT NULL,player1_id INTEGER,player2_id INTEGER,winner_id INTEGER,score1 REAL,score2 REAL,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(tournament_id,round_name,match_no),FOREIGN KEY(tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE,FOREIGN KEY(player1_id) REFERENCES players(id) ON DELETE SET NULL,FOREIGN KEY(player2_id) REFERENCES players(id) ON DELETE SET NULL,FOREIGN KEY(winner_id) REFERENCES players(id) ON DELETE SET NULL);
`);
for (const [table,column,def] of [
  ['tournaments','game_id','INTEGER'],['tournaments','password_hash','TEXT'],['tournaments','password_salt','TEXT'],['tournaments','status',"TEXT NOT NULL DEFAULT 'draft'"],['tournaments','created_by','TEXT'],['tournaments','updated_at','TEXT DEFAULT CURRENT_TIMESTAMP'],['results','kd','REAL'],['results','created_at','TEXT DEFAULT CURRENT_TIMESTAMP']
] as const) try { db.prepare(`ALTER TABLE ${table} ADD COLUMN ${column} ${def}`).run(); } catch (_) {}

function hashPassword(p:string,s:string){return crypto.scryptSync(p,s,64).toString('hex');}
function makePassword(p:string){const salt=crypto.randomBytes(16).toString('hex'); return {salt,hash:hashPassword(p,salt)};}
function verifyPassword(p:string,h:string,s:string){const a=Buffer.from(hashPassword(p,s),'hex'),b=Buffer.from(h,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b);}
function getGame(n:string){return db.prepare('SELECT * FROM games WHERE name=? COLLATE NOCASE').get(n) as any;}
function getTournament(n:string){return db.prepare('SELECT t.*,g.name game_name FROM tournaments t LEFT JOIN games g ON g.id=t.game_id WHERE t.name=? COLLATE NOCASE').get(n) as any;}
function getTournamentById(id:number){return db.prepare('SELECT t.*,g.name game_name FROM tournaments t LEFT JOIN games g ON g.id=t.game_id WHERE t.id=?').get(id) as any;}
function getPlayer(n:string){return db.prepare('SELECT * FROM players WHERE name=? COLLATE NOCASE').get(n) as any;}
function ensurePlayer(n:string,d?:string|null){let p=getPlayer(n);if(!p){const r=db.prepare('INSERT INTO players(name,discord_id) VALUES(?,?)').run(n.trim(),d??null);p={id:Number(r.lastInsertRowid),name:n.trim(),discord_id:d??null};}else if(d&&p.discord_id!==d){db.prepare('UPDATE players SET discord_id=? WHERE id=?').run(d,p.id);p.discord_id=d;}return p;}
function addParticipant(t:number,p:number,seed?:number){db.prepare('INSERT OR IGNORE INTO tournament_players(tournament_id,player_id,seed) VALUES(?,?,?)').run(t,p,seed??null);}
function clean(v:string,max=3900){return v.length>max?v.slice(0,max-25)+'\n…truncated':v;}
function parseResults(raw:string){const e=raw.split(',').map(x=>x.trim()).filter(Boolean).map((x,index)=>{const m=x.match(/^(?:(\d+)\s*:\s*)?(.+?)\s*=\s*(-?\d+(?:\.\d+)?)$/);return m?{position:m[1]?Number(m[1]):null,name:m[2].trim(),points:Number(m[3]),inputOrder:index}:null;});if(!e.length||e.some(x=>!x||!x.name||!Number.isFinite(x.points)))return null;const a=e as {position:number|null,name:string,points:number,inputOrder:number}[],s=[...a].sort((x,y)=>y.points-x.points||x.inputOrder-y.inputOrder);return a.map(x=>({...x,position:x.position??s.findIndex(y=>y===x)+1}));}

const commands=[
new SlashCommandBuilder().setName('help').setDescription('Show TGS Game Tracker commands'),
new SlashCommandBuilder().setName('game').setDescription('Create a game').addStringOption(o=>o.setName('name').setDescription('Game name').setRequired(true)),
new SlashCommandBuilder().setName('tournament').setDescription('Create a password-protected tournament').addStringOption(o=>o.setName('name').setDescription('Tournament name').setRequired(true)).addStringOption(o=>o.setName('game').setDescription('Game name').setRequired(true)).addStringOption(o=>o.setName('password').setDescription('Tournament password').setRequired(true).setMinLength(4)).addStringOption(o=>o.setName('confirm_password').setDescription('Repeat tournament password').setRequired(true).setMinLength(4)),
new SlashCommandBuilder().setName('tournament-manage').setDescription('Open tournament management panel'),
new SlashCommandBuilder().setName('tournament-player').setDescription('Manage tournament players').addSubcommand(s=>s.setName('add').setDescription('Add player').addStringOption(o=>o.setName('tournament').setDescription('Tournament').setRequired(true)).addStringOption(o=>o.setName('player').setDescription('Player name').setRequired(true)).addUserOption(o=>o.setName('discord').setDescription('Discord account'))).addSubcommand(s=>s.setName('remove').setDescription('Remove player').addStringOption(o=>o.setName('tournament').setDescription('Tournament').setRequired(true)).addStringOption(o=>o.setName('player').setDescription('Player name').setRequired(true))),
new SlashCommandBuilder().setName('player').setDescription('Register/link player').addStringOption(o=>o.setName('name').setDescription('Player name').setRequired(true)).addUserOption(o=>o.setName('discord').setDescription('Discord account')),
new SlashCommandBuilder().setName('race').setDescription('Record race results').addStringOption(o=>o.setName('tournament').setDescription('Tournament').setRequired(true)).addIntegerOption(o=>o.setName('number').setDescription('Race number').setRequired(true).setMinValue(1)).addStringOption(o=>o.setName('track').setDescription('Track/map').setRequired(true)).addStringOption(o=>o.setName('results').setDescription('Player=points,Player=points').setRequired(true)),
new SlashCommandBuilder().setName('tournaments').setDescription('List tournaments').addStringOption(o=>o.setName('game').setDescription('Optional game filter')),
new SlashCommandBuilder().setName('players').setDescription('List registered players'),
new SlashCommandBuilder().setName('tournament-report').setDescription('Full tournament report').addStringOption(o=>o.setName('tournament').setDescription('Tournament').setRequired(true)),
new SlashCommandBuilder().setName('player-report').setDescription('Full player report').addStringOption(o=>o.setName('player').setDescription('Player').setRequired(true)).addStringOption(o=>o.setName('game').setDescription('Optional game filter')),
new SlashCommandBuilder().setName('player-history').setDescription('Player race history').addStringOption(o=>o.setName('player').setDescription('Player').setRequired(true)).addStringOption(o=>o.setName('game').setDescription('Optional game filter')),
new SlashCommandBuilder().setName('game-report').setDescription('Game-wide report').addStringOption(o=>o.setName('game').setDescription('Game').setRequired(true))].map(x=>x.toJSON());

async function registerCommands(){const rest=new REST({version:'10'}).setToken(token!);await rest.put(Routes.applicationGuildCommands(clientId!,guildId!),{body:commands});console.log(`Registered ${commands.length} slash commands.`);}
const client=new Client({intents:[GatewayIntentBits.Guilds]});

function managementPanel(){const rows=db.prepare('SELECT t.id,t.name,g.name game_name,t.status FROM tournaments t LEFT JOIN games g ON g.id=t.game_id ORDER BY t.created_at DESC LIMIT 25').all() as any[];if(!rows.length)return{content:'❌ No tournaments found. Create one with `/tournament`.'};const menu=new StringSelectMenuBuilder().setCustomId('tgs:tournament-select').setPlaceholder('Select a tournament').addOptions(rows.map(t=>({label:t.name.slice(0,100),value:String(t.id),description:`${t.game_name||'General'} • ${t.status}`.slice(0,100)})));return{content:'🏆 **TGS Tournament Manager**\nSelect a tournament below.',components:[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(menu)]};}
function managerButtons(id:number){return new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`tgs:update:${id}`).setLabel('Update').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`tgs:delete:${id}`).setLabel('Delete').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId(`tgs:fixtures:${id}`).setLabel('Create Fixtures').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`tgs:report:${id}`).setLabel('Report').setStyle(ButtonStyle.Secondary));}
function passwordModal(action:string,id:number){const m=new ModalBuilder().setCustomId(`tgs:password:${action}:${id}`).setTitle(`${action[0].toUpperCase()+action.slice(1)} Tournament`);m.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('password').setLabel('Tournament password').setStyle(TextInputStyle.Short).setRequired(true).setMinLength(4)));return m;}
async function passwordOk(i:ModalSubmitInteraction,id:number){const t=getTournamentById(id);if(!t){await i.reply({content:'❌ Tournament not found.',ephemeral:true});return null;}const p=i.fields.getTextInputValue('password');if(!t.password_hash||!t.password_salt||!verifyPassword(p,t.password_hash,t.password_salt)){await i.reply({content:'❌ Incorrect tournament password.',ephemeral:true});return null;}return t;}

async function sendTournamentReport(i:ChatInputCommandInteraction|ButtonInteraction,tName:string){const t=getTournament(tName);if(!t){await i.reply({content:'❌ Tournament not found.',ephemeral:true});return;}const rows=db.prepare(`SELECT p.name,SUM(r.points) total,COUNT(r.id) races,MIN(r.position) best_position,AVG(r.position) avg_position FROM results r JOIN players p ON p.id=r.player_id JOIN races ra ON ra.id=r.race_id WHERE ra.tournament_id=? GROUP BY p.id ORDER BY total DESC,best_position ASC`).all(t.id) as any[];const races=db.prepare('SELECT race_no,track FROM races WHERE tournament_id=? ORDER BY race_no').all(t.id) as any[];const parts=db.prepare('SELECT p.name FROM tournament_players tp JOIN players p ON p.id=tp.player_id WHERE tp.tournament_id=? ORDER BY p.name').all(t.id) as any[];const standings=rows.length?rows.map((r,n)=>`${n+1}. **${r.name}** — **${r.total} pts** • ${r.races} races • Best P${r.best_position??'-'} • Avg P${Number(r.avg_position||0).toFixed(1)}`).join('\n'):'No results recorded.';const pList=parts.length?parts.map(r=>`• ${r.name}`).join('\n'):'No participants.';const rList=races.length?races.map(r=>`Race ${r.race_no} — ${r.track}`).join('\n'):'No races recorded.';await i.reply({embeds:[new EmbedBuilder().setTitle(`🏆 ${t.name}`).setDescription(clean(`🎮 **Game:** ${t.game_name||'General'}\n📌 **Status:** ${t.status}\n\n**PARTICIPANTS**\n${pList}\n\n**STANDINGS**\n${standings}\n\n**RACES**\n${rList}`))]});}

function createFixtures(tournamentId:number){const players=db.prepare('SELECT p.id,p.name,tp.seed FROM tournament_players tp JOIN players p ON p.id=tp.player_id WHERE tp.tournament_id=? ORDER BY CASE WHEN tp.seed IS NULL THEN 1 ELSE 0 END,tp.seed,p.name').all(tournamentId) as any[];if(players.length<2)throw new Error('At least 2 tournament players are required.');db.prepare('DELETE FROM matches WHERE tournament_id=?').run(tournamentId);const size=2**Math.ceil(Math.log2(players.length));const slots=[...players];while(slots.length<size)slots.push(null as any);const rounds=Math.log2(size),roundName=rounds===1?'Final':rounds===2?'Semifinal':rounds===3?'Quarterfinal':'Round of '+size;const tx=db.transaction(()=>{for(let n=0;n<size;n+=2){const a=slots[n],b=slots[n+1];const winner=a&&!b?a:!a&&b?b:null,status=winner?'bye':'pending';db.prepare('INSERT INTO matches(tournament_id,round_name,match_no,player1_id,player2_id,winner_id,status) VALUES(?,?,?,?,?,?,?)').run(tournamentId,roundName,n/2+1,a?.id??null,b?.id??null,winner?.id??null,status);}db.prepare('UPDATE tournaments SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run('fixtures_created',tournamentId);});tx();return{players:players.length,size,roundName};}

async function handleCommand(i:ChatInputCommandInteraction){
if(i.commandName==='help'){await i.reply('**TGS Game Tracker**\n\n`/game` • create game\n`/tournament` • create password-protected tournament\n`/tournament-manage` • manage tournament\n`/tournament-player add/remove` • manage participants\n`/player` • register/link player\n`/race` • save race result\n`/tournaments` / `/players` • lists\n`/tournament-report` / `/player-report` / `/player-history` / `/game-report` • reports');return;}
if(i.commandName==='game'){const n=i.options.getString('name',true).trim();try{db.prepare('INSERT INTO games(name) VALUES(?)').run(n);await i.reply(`🎮 Game **${n}** created.`);}catch{await i.reply(`❌ Game **${n}** already exists.`);}return;}
if(i.commandName==='tournament'){const n=i.options.getString('name',true).trim(),gn=i.options.getString('game',true).trim(),p=i.options.getString('password',true),c=i.options.getString('confirm_password',true);if(p!==c){await i.reply({content:'❌ Password confirmation does not match.',ephemeral:true});return;}const g=getGame(gn);if(!g){await i.reply({content:`❌ Game **${gn}** not found. Create it first with /game.`,ephemeral:true});return;}try{const x=makePassword(p);db.prepare('INSERT INTO tournaments(name,game_id,password_hash,password_salt,status,created_by) VALUES(?,?,?,?,?,?)').run(n,g.id,x.hash,x.salt,'draft',i.user.id);await i.reply({content:`🏆 Tournament **${n}** created under 🎮 **${g.name}**.\n🔐 Password saved securely.`,ephemeral:true});}catch{await i.reply({content:'❌ Tournament name already exists.',ephemeral:true});}return;}
if(i.commandName==='tournament-manage'){await i.reply({...managementPanel(),ephemeral:true});return;}
if(i.commandName==='player'){const n=i.options.getString('name',true).trim(),u=i.options.getUser('discord');ensurePlayer(n,u?.id);await i.reply(`👤 Player **${n}** registered${u?` and linked to ${u}.`:'.'}`);return;}
if(i.commandName==='tournament-player'){const sub=i.options.getSubcommand(),t=getTournament(i.options.getString('tournament',true)),n=i.options.getString('player',true).trim();if(!t){await i.reply('❌ Tournament not found.');return;}if(sub==='add'){const u=i.options.getUser('discord'),p=ensurePlayer(n,u?.id);addParticipant(t.id,p.id);await i.reply(`✅ **${p.name}** added to **${t.name}**.`);return;}const p=getPlayer(n);if(!p){await i.reply('❌ Player not found.');return;}const r=db.prepare('DELETE FROM tournament_players WHERE tournament_id=? AND player_id=?').run(t.id,p.id);await i.reply(r.changes?`✅ **${p.name}** removed from **${t.name}**.`:'❌ Player is not registered in this tournament.');return;}
if(i.commandName==='race'){const t=getTournament(i.options.getString('tournament',true));if(!t){await i.reply('❌ Tournament not found.');return;}const num=i.options.getInteger('number',true),track=i.options.getString('track',true).trim(),parsed=parseResults(i.options.getString('results',true));if(!parsed){await i.reply('❌ Invalid results.');return;}try{db.transaction(()=>{const race=db.prepare('INSERT INTO races(tournament_id,race_no,track) VALUES(?,?,?)').run(t.id,num,track);for(const e of parsed){const p=ensurePlayer(e.name);addParticipant(t.id,p.id);db.prepare('INSERT INTO results(race_id,player_id,points,position) VALUES(?,?,?,?)').run(race.lastInsertRowid,p.id,e.points,e.position);})();await i.reply(`🏁 Race **${num}** recorded for **${t.name}**.`);}catch(e:any){await i.reply(`❌ Could not record race: ${e?.message||'unknown error'}`);}return;}
if(i.commandName==='tournaments'){const gn=i.options.getString('game'),rows=gn?db.prepare('SELECT t.name,g.name game_name,t.status FROM tournaments t JOIN games g ON g.id=t.game_id WHERE g.name=? COLLATE NOCASE ORDER BY t.created_at DESC').all(gn) as any[]:db.prepare('SELECT t.name,g.name game_name,t.status FROM tournaments t LEFT JOIN games g ON g.id=t.game_id ORDER BY t.created_at DESC').all() as any[];await i.reply({embeds:[new EmbedBuilder().setTitle(gn?`🏆 ${gn} Tournaments`:'🏆 All Tournaments').setDescription(clean(rows.length?rows.map((r,n)=>`${n+1}. **${r.name}** — 🎮 ${r.game_name||'General'} • ${r.status}`).join('\n'):'No tournaments found.'))]});return;}
if(i.commandName==='players'){const rows=db.prepare('SELECT p.name,COUNT(DISTINCT r.id) races,COALESCE(SUM(r.points),0) points FROM players p LEFT JOIN results r ON r.player_id=p.id GROUP BY p.id ORDER BY points DESC,p.name').all() as any[];await i.reply({embeds:[new EmbedBuilder().setTitle('👥 TGS Players').setDescription(clean(rows.length?rows.map((r,n)=>`${n+1}. **${r.name}** — ${r.points} pts • ${r.races} races`).join('\n'):'No players found.'))]});return;}
if(i.commandName==='tournament-report'){await sendTournamentReport(i,i.options.getString('tournament',true));return;}
if(i.commandName==='player-report'||i.commandName==='player-history'){const n=i.options.getString('player',true),gn=i.options.getString('game'),p=getPlayer(n);if(!p){await i.reply('❌ Player not found.');return;}const rows=db.prepare(`SELECT t.name tournament,g.name game_name,ra.race_no,ra.track,r.points,r.position FROM results r JOIN races ra ON ra.id=r.race_id JOIN tournaments t ON t.id=ra.tournament_id LEFT JOIN games g ON g.id=t.game_id WHERE r.player_id=? ${gn?'AND g.name=? COLLATE NOCASE':''} ORDER BY ra.created_at DESC,ra.race_no DESC`).all(...(gn?[p.id,gn]:[p.id])) as any[];if(i.commandName==='player-history'){await i.reply({embeds:[new EmbedBuilder().setTitle(`📋 ${p.name} History`).setDescription(clean(rows.length?rows.map(r=>`🎮 ${r.game_name||'General'} • **${r.tournament}** • Race ${r.race_no} • ${r.track} — **P${r.position??'-'} / ${r.points} pts**`).join('\n'):'No races recorded.'))]});return;}const total=rows.reduce((s,r)=>s+Number(r.points),0),ts=new Set(rows.map(r=>r.tournament)).size,wins=rows.filter(r=>Number(r.position)===1).length;await i.reply({embeds:[new EmbedBuilder().setTitle(`📊 ${p.name} Report`).setDescription(clean(`**Total Points:** ${total}\n**Tournaments:** ${ts}\n**Races:** ${rows.length}\n**P1 Finishes:** ${wins}\n\n${rows.map(r=>`🎮 ${r.game_name||'General'} • ${r.tournament} • Race ${r.race_no} — P${r.position??'-'}, ${r.points} pts`).join('\n')||'No records.'}`))]});return;}
if(i.commandName==='game-report'){const g=getGame(i.options.getString('game',true));if(!g){await i.reply('❌ Game not found.');return;}const ts=db.prepare('SELECT t.name,COUNT(DISTINCT ra.id) races FROM tournaments t LEFT JOIN races ra ON ra.tournament_id=t.id WHERE t.game_id=? GROUP BY t.id ORDER BY t.created_at DESC').all(g.id) as any[],ps=db.prepare('SELECT p.name,SUM(r.points) points,COUNT(r.id) races FROM results r JOIN players p ON p.id=r.player_id JOIN races ra ON ra.id=r.race_id JOIN tournaments t ON t.id=ra.tournament_id WHERE t.game_id=? GROUP BY p.id ORDER BY points DESC').all(g.id) as any[];await i.reply({embeds:[new EmbedBuilder().setTitle(`🎮 ${g.name} Report`).setDescription(clean(`**Tournaments**\n${ts.length?ts.map((r,n)=>`${n+1}. **${r.name}** — ${r.races} races`).join('\n'):'None'}\n\n**Players**\n${ps.length?ps.map((r,n)=>`${n+1}. **${r.name}** — ${r.points} pts • ${r.races} races`).join('\n'):'None'}`))]});return;}}

async function handleSelect(i:StringSelectMenuInteraction){if(i.customId!=='tgs:tournament-select')return;const id=Number(i.values[0]),t=getTournamentById(id);if(!t){await i.update({content:'❌ Tournament not found.',components:[]});return;}await i.update({content:`🏆 **${t.name}**\n🎮 **${t.game_name||'General'}**\n📌 **${t.status}**\n\nChoose an action:`,components:[managerButtons(id)]});}
async function handleButton(i:ButtonInteraction){const [p,a,idS]=i.customId.split(':');if(p!=='tgs')return;const id=Number(idS),t=getTournamentById(id);if(!t){await i.reply({content:'❌ Tournament not found.',ephemeral:true});return;}if(a==='report'){await sendTournamentReport(i,t.name);return;}if(['update','delete','fixtures'].includes(a)){await i.showModal(passwordModal(a,id));}}
async function handleModal(i:ModalSubmitInteraction){const parts=i.customId.split(':');if(parts[0]!=='tgs'||parts[1]!=='password')return;const a=parts[2],id=Number(parts[3]),t=await passwordOk(i,id);if(!t)return;if(a==='delete'){db.prepare('DELETE FROM tournaments WHERE id=?').run(id);await i.reply({content:`🗑️ Tournament **${t.name}** deleted.`,ephemeral:true});return;}if(a==='fixtures'){try{const r=createFixtures(id);await i.reply({content:`✅ Fixtures created for **${t.name}**.\n👥 ${r.players} players • Bracket size ${r.size} • ${r.roundName}`,ephemeral:true});}catch(e:any){await i.reply({content:`❌ ${e?.message||'Could not create fixtures.'}`,ephemeral:true});}return;}if(a==='update'){const m=new ModalBuilder().setCustomId(`tgs:update-form:${id}`).setTitle('Update Tournament');m.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('name').setLabel('Tournament name').setStyle(TextInputStyle.Short).setRequired(true).setValue(t.name)),new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('game').setLabel('Game').setStyle(TextInputStyle.Short).setRequired(true).setValue(t.game_name||'General')),new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('status').setLabel('Status').setStyle(TextInputStyle.Short).setRequired(true).setValue(t.status)));await i.showModal(m);return;}}
async function handleUpdateForm(i:ModalSubmitInteraction){const id=Number(i.customId.split(':')[2]),t=getTournamentById(id);if(!t){await i.reply({content:'❌ Tournament not found.',ephemeral:true});return;}const n=i.fields.getTextInputValue('name').trim(),gn=i.fields.getTextInputValue('game').trim(),status=i.fields.getTextInputValue('status').trim().toLowerCase(),g=getGame(gn);if(!n||!g){await i.reply({content:'❌ Valid tournament name and existing game are required.',ephemeral:true});return;}if(!['draft','live','completed','fixtures_created'].includes(status)){await i.reply({content:'❌ Status must be draft, live, completed or fixtures_created.',ephemeral:true});return;}try{db.prepare('UPDATE tournaments SET name=?,game_id=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(n,g.id,status,id);await i.reply({content:`✅ Tournament updated: **${n}** • 🎮 **${g.name}** • **${status}**`,ephemeral:true});}catch{await i.reply({content:'❌ Update failed. Tournament name may already be used.',ephemeral:true});}}

client.once('ready',async c=>{console.log(`Logged in as ${c.user.tag}`);try{await registerCommands();}catch(e){console.error('Command registration failed:',e);}});
client.on('interactionCreate',async(i:Interaction)=>{try{if(i.isChatInputCommand())await handleCommand(i);else if(i.isStringSelectMenu())await handleSelect(i);else if(i.isButton())await handleButton(i);else if(i.isModalSubmit()&&i.customId.startsWith('tgs:update-form:'))await handleUpdateForm(i);else if(i.isModalSubmit())await handleModal(i);}catch(e:any){console.error('Interaction error:',e);if(i.isRepliable()){const m='❌ Something went wrong while processing this action.';if(i.replied||i.deferred)await i.followUp({content:m,ephemeral:true}).catch(()=>{});else await i.reply({content:m,ephemeral:true}).catch(()=>{});}}});
client.login(token);
