import 'dotenv/config';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {
  ActionRowBuilder, ButtonBuilder, ButtonStyle, ChannelType, Client, EmbedBuilder,
  GatewayIntentBits, ModalBuilder, REST, Routes, SlashCommandBuilder,
  StringSelectMenuBuilder, TextInputBuilder, TextInputStyle,
  type ButtonInteraction, type ChatInputCommandInteraction, type Interaction,
  type ModalSubmitInteraction, type StringSelectMenuInteraction,
} from 'discord.js';
import Database from 'better-sqlite3';

const token = process.env.DISCORD_TOKEN;
const clientId = process.env.CLIENT_ID;
const guildId = process.env.GUILD_ID;
if (!token || !clientId || !guildId) throw new Error('Missing DISCORD_TOKEN, CLIENT_ID or GUILD_ID in .env');

const dbPath = process.env.DATABASE_PATH || './data/tgs-tracker.db';
fs.mkdirSync(path.dirname(dbPath), { recursive: true });
const db = new Database(dbPath);
db.pragma('journal_mode = WAL');
db.pragma('foreign_keys = ON');

db.exec(`
CREATE TABLE IF NOT EXISTS games(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE COLLATE NOCASE,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tournaments(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE COLLATE NOCASE,game_id INTEGER,password_hash TEXT,password_salt TEXT,status TEXT NOT NULL DEFAULT 'draft',created_by TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(game_id) REFERENCES games(id));
CREATE TABLE IF NOT EXISTS players(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE COLLATE NOCASE,discord_id TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tournament_players(tournament_id INTEGER NOT NULL,player_id INTEGER NOT NULL,seed INTEGER,joined_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(tournament_id,player_id),FOREIGN KEY(tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE,FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS races(id INTEGER PRIMARY KEY AUTOINCREMENT,tournament_id INTEGER NOT NULL,race_no INTEGER NOT NULL,track TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(tournament_id,race_no),FOREIGN KEY(tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS results(id INTEGER PRIMARY KEY AUTOINCREMENT,race_id INTEGER NOT NULL,player_id INTEGER NOT NULL,points REAL NOT NULL DEFAULT 0,position INTEGER,kd REAL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(race_id) REFERENCES races(id) ON DELETE CASCADE,FOREIGN KEY(player_id) REFERENCES players(id) ON DELETE CASCADE,UNIQUE(race_id,player_id));
CREATE TABLE IF NOT EXISTS matches(id INTEGER PRIMARY KEY AUTOINCREMENT,tournament_id INTEGER NOT NULL,round_no INTEGER NOT NULL DEFAULT 0,round_name TEXT NOT NULL,match_no INTEGER NOT NULL,player1_id INTEGER,player2_id INTEGER,winner_id INTEGER,score1 REAL,score2 REAL,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(tournament_id,round_no,match_no),FOREIGN KEY(player1_id) REFERENCES players(id) ON DELETE SET NULL,FOREIGN KEY(player2_id) REFERENCES players(id) ON DELETE SET NULL,FOREIGN KEY(winner_id) REFERENCES players(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS birthdays(discord_id TEXT PRIMARY KEY,month INTEGER NOT NULL,day INTEGER NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS birthday_config(guild_id TEXT PRIMARY KEY,channel_id TEXT,enabled INTEGER NOT NULL DEFAULT 1,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS birthday_announcements(guild_id TEXT NOT NULL,discord_id TEXT NOT NULL,year INTEGER NOT NULL,announced_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(guild_id,discord_id,year));
`);

for (const [table, column, definition] of [
  ['tournaments','game_id','INTEGER'], ['tournaments','password_hash','TEXT'], ['tournaments','password_salt','TEXT'],
  ['tournaments','status',"TEXT NOT NULL DEFAULT 'draft'"], ['tournaments','created_by','TEXT'],
  ['tournaments','updated_at','TEXT DEFAULT CURRENT_TIMESTAMP'], ['results','kd','REAL'], ['results','created_at','TEXT DEFAULT CURRENT_TIMESTAMP'],
  ['matches','round_no','INTEGER NOT NULL DEFAULT 0'],
] as const) {
  try { db.prepare(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`).run(); } catch (_) { /* exists */ }
}
try { db.prepare("UPDATE matches SET round_no=0 WHERE round_no IS NULL").run(); } catch (_) {}

function hashPassword(password:string, salt:string){ return crypto.scryptSync(password,salt,64).toString('hex'); }
function makePassword(password:string){ const salt=crypto.randomBytes(16).toString('hex'); return {salt,hash:hashPassword(password,salt)}; }
function verifyPassword(password:string, hash:string, salt:string){ const a=Buffer.from(hashPassword(password,salt),'hex'); const b=Buffer.from(hash,'hex'); return a.length===b.length && crypto.timingSafeEqual(a,b); }
function clean(v:string,max=3900){ return v.length>max ? v.slice(0,max-30)+'\n…truncated' : v; }
function getGame(name:string){ return db.prepare('SELECT * FROM games WHERE name=? COLLATE NOCASE').get(name) as any; }
function getTournament(name:string){ return db.prepare('SELECT t.*,g.name game_name FROM tournaments t LEFT JOIN games g ON g.id=t.game_id WHERE t.name=? COLLATE NOCASE').get(name) as any; }
function getTournamentById(id:number){ return db.prepare('SELECT t.*,g.name game_name FROM tournaments t LEFT JOIN games g ON g.id=t.game_id WHERE t.id=?').get(id) as any; }
function getPlayer(name:string){ return db.prepare('SELECT * FROM players WHERE name=? COLLATE NOCASE').get(name) as any; }
function ensurePlayer(name:string,discordId?:string|null){
  const cleanName=name.trim(); if(!cleanName) throw new Error('Player name cannot be empty.');
  let p=getPlayer(cleanName);
  if(!p){ const r=db.prepare('INSERT INTO players(name,discord_id) VALUES(?,?)').run(cleanName,discordId??null); p={id:Number(r.lastInsertRowid),name:cleanName,discord_id:discordId??null}; }
  else if(discordId && p.discord_id!==discordId){ db.prepare('UPDATE players SET discord_id=? WHERE id=?').run(discordId,p.id); p.discord_id=discordId; }
  return p;
}
function addParticipant(tournamentId:number,playerId:number,seed?:number){ db.prepare('INSERT OR IGNORE INTO tournament_players(tournament_id,player_id,seed) VALUES(?,?,?)').run(tournamentId,playerId,seed??null); }
function isManager(i:{member:any}){ return Boolean(i.member?.permissions?.has?.('ManageGuild') || i.member?.permissions?.has?.('Administrator')); }
function parseResults(raw:string){
  const entries=raw.split(',').map(x=>x.trim()).filter(Boolean).map((x,index)=>{ const m=x.match(/^(?:(\d+)\s*:\s*)?(.+?)\s*=\s*(-?\d+(?:\.\d+)?)$/); return m?{position:m[1]?Number(m[1]):null,name:m[2].trim(),points:Number(m[3]),inputOrder:index}:null; });
  if(!entries.length || entries.some(x=>!x||!x.name||!Number.isFinite(x.points))) return null;
  const valid=entries as {position:number|null,name:string,points:number,inputOrder:number}[];
  const sorted=[...valid].sort((a,b)=>b.points-a.points||a.inputOrder-b.inputOrder);
  return valid.map(e=>({...e,position:e.position??sorted.findIndex(x=>x===e)+1}));
}

const commands=[
  new SlashCommandBuilder().setName('help').setDescription('Show TGS Game Tracker commands'),
  new SlashCommandBuilder().setName('game').setDescription('Create a game').addStringOption(o=>o.setName('name').setDescription('Game name').setRequired(true)),
  new SlashCommandBuilder().setName('tournament').setDescription('Create a password-protected tournament').addStringOption(o=>o.setName('name').setDescription('Tournament name').setRequired(true)).addStringOption(o=>o.setName('game').setDescription('Select a game created with /game').setRequired(true).setAutocomplete(true)).addStringOption(o=>o.setName('password').setDescription('Tournament password').setRequired(true).setMinLength(4)).addStringOption(o=>o.setName('confirm_password').setDescription('Repeat password').setRequired(true).setMinLength(4)),
  new SlashCommandBuilder().setName('tournament-manage').setDescription('Open tournament management panel'),
  new SlashCommandBuilder().setName('tournament-player').setDescription('Manage tournament players').addSubcommand(s=>s.setName('add').setDescription('Add player').addStringOption(o=>o.setName('tournament').setDescription('Tournament').setRequired(true)).addStringOption(o=>o.setName('player').setDescription('Player name').setRequired(true)).addUserOption(o=>o.setName('discord').setDescription('Discord account'))).addSubcommand(s=>s.setName('remove').setDescription('Remove player').addStringOption(o=>o.setName('tournament').setDescription('Tournament').setRequired(true)).addStringOption(o=>o.setName('player').setDescription('Player name').setRequired(true))),
  new SlashCommandBuilder().setName('player').setDescription('Register/link player').addStringOption(o=>o.setName('name').setDescription('Player name').setRequired(true)).addUserOption(o=>o.setName('discord').setDescription('Discord account')),
  new SlashCommandBuilder().setName('race').setDescription('Record race results').addStringOption(o=>o.setName('tournament').setDescription('Tournament').setRequired(true)).addIntegerOption(o=>o.setName('number').setDescription('Race number').setRequired(true).setMinValue(1)).addStringOption(o=>o.setName('track').setDescription('Track/map').setRequired(true)).addStringOption(o=>o.setName('results').setDescription('Player=points,Player=points').setRequired(true)),
  new SlashCommandBuilder().setName('match-result').setDescription('Record a fixture result and advance the winner').addStringOption(o=>o.setName('tournament').setDescription('Tournament').setRequired(true)).addIntegerOption(o=>o.setName('round').setDescription('Round number, starting at 1').setRequired(true).setMinValue(1)).addIntegerOption(o=>o.setName('match').setDescription('Match number').setRequired(true).setMinValue(1)).addStringOption(o=>o.setName('winner').setDescription('Winner player name').setRequired(true)).addNumberOption(o=>o.setName('score1').setDescription('Player 1 score').setRequired(true)).addNumberOption(o=>o.setName('score2').setDescription('Player 2 score').setRequired(true)),
  new SlashCommandBuilder().setName('fixtures').setDescription('Show tournament fixtures').addStringOption(o=>o.setName('tournament').setDescription('Tournament').setRequired(true).setAutocomplete(true)),
  new SlashCommandBuilder().setName('tournaments').setDescription('List tournaments').addStringOption(o=>o.setName('game').setDescription('Optional game filter')),
  new SlashCommandBuilder().setName('players').setDescription('List registered players'),
  new SlashCommandBuilder().setName('tournament-report').setDescription('Full tournament report').addStringOption(o=>o.setName('tournament').setDescription('Tournament').setRequired(true)),
  new SlashCommandBuilder().setName('player-report').setDescription('Full player report').addStringOption(o=>o.setName('player').setDescription('Player').setRequired(true)).addStringOption(o=>o.setName('game').setDescription('Optional game filter')),
  new SlashCommandBuilder().setName('player-history').setDescription('Player race history').addStringOption(o=>o.setName('player').setDescription('Player').setRequired(true)).addStringOption(o=>o.setName('game').setDescription('Optional game filter')),
  new SlashCommandBuilder().setName('game-report').setDescription('Game-wide report').addStringOption(o=>o.setName('game').setDescription('Game').setRequired(true)),
  new SlashCommandBuilder().setName('birthday').setDescription('Manage automatic birthdays').addSubcommand(s=>s.setName('set').setDescription('Set a member birthday').addUserOption(o=>o.setName('user').setDescription('Discord member').setRequired(true)).addIntegerOption(o=>o.setName('month').setDescription('Month 1-12').setRequired(true).setMinValue(1).setMaxValue(12)).addIntegerOption(o=>o.setName('day').setDescription('Day 1-31').setRequired(true).setMinValue(1).setMaxValue(31))).addSubcommand(s=>s.setName('remove').setDescription('Remove a member birthday').addUserOption(o=>o.setName('user').setDescription('Discord member').setRequired(true))).addSubcommand(s=>s.setName('channel').setDescription('Set birthday announcement channel').addChannelOption(o=>o.setName('channel').setDescription('Text channel').addChannelTypes(ChannelType.GuildText).setRequired(true))).addSubcommand(s=>s.setName('list').setDescription('List configured birthdays')),
].map(x=>x.toJSON());

async function registerCommands(){ const rest=new REST({version:'10'}).setToken(token!); await rest.put(Routes.applicationGuildCommands(clientId!,guildId!),{body:commands}); console.log(`Registered ${commands.length} slash commands.`); }
const client=new Client({intents:[GatewayIntentBits.Guilds]});

function managerPanel(){
  const rows=db.prepare('SELECT t.id,t.name,g.name game_name,t.status FROM tournaments t LEFT JOIN games g ON g.id=t.game_id ORDER BY t.created_at DESC LIMIT 25').all() as any[];
  if(!rows.length) return {content:'❌ No tournaments found. Create one with `/tournament`.'};
  const menu=new StringSelectMenuBuilder().setCustomId('tgs:tournament-select').setPlaceholder('Select a tournament').addOptions(rows.map(t=>({label:t.name.slice(0,100),value:String(t.id),description:`${t.game_name||'General'} • ${t.status}`.slice(0,100)})));
  return {content:'🏆 **TGS Tournament Manager**\nSelect a tournament to manage it.',components:[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(menu)]};
}
function managerButtons(id:number){ return new ActionRowBuilder<ButtonBuilder>().addComponents(
  new ButtonBuilder().setCustomId(`tgs:update:${id}`).setLabel('Update').setStyle(ButtonStyle.Primary),
  new ButtonBuilder().setCustomId(`tgs:delete:${id}`).setLabel('Delete').setStyle(ButtonStyle.Danger),
  new ButtonBuilder().setCustomId(`tgs:fixtures:${id}`).setLabel('Create Fixtures').setStyle(ButtonStyle.Success),
  new ButtonBuilder().setCustomId(`tgs:report:${id}`).setLabel('Report').setStyle(ButtonStyle.Secondary)); }
function passwordModal(action:string,id:number){ const m=new ModalBuilder().setCustomId(`tgs:password:${action}:${id}`).setTitle(`${action==='delete'?'Delete':action==='fixtures'?'Create Fixtures':'Update'} Tournament`); m.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('password').setLabel('Tournament password').setStyle(TextInputStyle.Short).setRequired(true).setMinLength(4))); return m; }
async function passwordOk(i:ModalSubmitInteraction,id:number){ const t=getTournamentById(id); if(!t){await i.reply({content:'❌ Tournament not found.',ephemeral:true});return null;} const p=i.fields.getTextInputValue('password'); if(!t.password_hash||!t.password_salt||!verifyPassword(p,t.password_hash,t.password_salt)){await i.reply({content:'❌ Incorrect tournament password.',ephemeral:true});return null;} return t; }

function roundName(totalSlots:number,round:number){ const totalRounds=Math.log2(totalSlots); const fromFinal=totalRounds-round; if(fromFinal===0)return 'Final'; if(fromFinal===1)return 'Semifinal'; if(fromFinal===2)return 'Quarterfinal'; return `Round of ${totalSlots/(2**round)}`; }
function createFixtures(tournamentId:number){
  const players=db.prepare('SELECT p.id,p.name,tp.seed FROM tournament_players tp JOIN players p ON p.id=tp.player_id WHERE tp.tournament_id=? ORDER BY CASE WHEN tp.seed IS NULL THEN 1 ELSE 0 END,tp.seed,p.name').all(tournamentId) as any[];
  if(players.length<2) throw new Error('At least 2 tournament players are required.');
  db.prepare('DELETE FROM matches WHERE tournament_id=?').run(tournamentId);
  const size=2**Math.ceil(Math.log2(players.length)); const slots=[...players]; while(slots.length<size)slots.push(null as any);
  const tx=db.transaction(()=>{ for(let n=0;n<size;n+=2){ const a=slots[n],b=slots[n+1]; const winner=a&&!b?a:!a&&b?b:null; const status=winner?'bye':'pending'; db.prepare('INSERT INTO matches(tournament_id,round_no,round_name,match_no,player1_id,player2_id,winner_id,status) VALUES(?,?,?,?,?,?,?,?)').run(tournamentId,1,roundName(size,1),n/2+1,a?.id??null,b?.id??null,winner?.id??null,status); } db.prepare("UPDATE tournaments SET status='fixtures_created',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(tournamentId); }); tx();
  autoAdvanceRound(tournamentId,1); return {players:players.length,size};
}
function autoAdvanceRound(tournamentId:number,round:number){
  const current=db.prepare('SELECT * FROM matches WHERE tournament_id=? AND round_no=? ORDER BY match_no').all(tournamentId,round) as any[];
  if(!current.length || current.some(m=>m.status==='pending')) return null;
  const t=getTournamentById(tournamentId); if(!t)return null;
  const winners=current.map(m=>m.winner_id).filter(Boolean) as number[];
  if(winners.length===1){ db.prepare("UPDATE tournaments SET status='completed',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(tournamentId); return {final:true,winnerId:winners[0]}; }
  const nextRound=round+1;
  const existing=db.prepare('SELECT COUNT(*) c FROM matches WHERE tournament_id=? AND round_no=?').get(tournamentId,nextRound) as any;
  if(existing.c>0)return null;
  const tx=db.transaction(()=>{ for(let n=0;n<winners.length;n+=2){ const a=winners[n] ? db.prepare('SELECT id,name FROM players WHERE id=?').get(winners[n]) as any : null; const b=winners[n+1] ? db.prepare('SELECT id,name FROM players WHERE id=?').get(winners[n+1]) as any : null; const winner=a&&!b?a:!a&&b?b:null; const status=winner?'bye':'pending'; const totalSlots=2**Math.ceil(Math.log2(Math.max(2,winners.length))); db.prepare('INSERT INTO matches(tournament_id,round_no,round_name,match_no,player1_id,player2_id,winner_id,status) VALUES(?,?,?,?,?,?,?,?)').run(tournamentId,nextRound,roundName(totalSlots,1),n/2+1,a?.id??null,b?.id??null,winner?.id??null,status); } db.prepare("UPDATE tournaments SET status='fixtures_created',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(tournamentId); }); tx();
  return autoAdvanceRound(tournamentId,nextRound);
}
function fixtureText(tournamentId:number){
  const rows=db.prepare(`SELECT m.round_no,m.round_name,m.match_no,m.status,p1.name p1,p2.name p2,w.name winner,m.score1,m.score2 FROM matches m LEFT JOIN players p1 ON p1.id=m.player1_id LEFT JOIN players p2 ON p2.id=m.player2_id LEFT JOIN players w ON w.id=m.winner_id WHERE m.tournament_id=? ORDER BY m.round_no,m.match_no`).all(tournamentId) as any[];
  if(!rows.length)return 'No fixtures generated.';
  return rows.map(m=>`**R${m.round_no} ${m.round_name} • Match ${m.match_no}** — ${m.p1||'BYE'} vs ${m.p2||'BYE'} • ${m.status==='completed'?`Winner: **${m.winner}** (${m.score1}-${m.score2})`:m.status==='bye'?`Bye: **${m.winner}**`:'Pending'}`).join('\n');
}

async function tournamentReport(i:ChatInputCommandInteraction|ButtonInteraction,name:string){
  const t=getTournament(name); if(!t){await i.reply({content:'❌ Tournament not found.',ephemeral:true});return;}
  const rows=db.prepare(`SELECT p.name,SUM(r.points) total,COUNT(r.id) races,MIN(r.position) best_position,AVG(r.position) avg_position FROM results r JOIN players p ON p.id=r.player_id JOIN races ra ON ra.id=r.race_id WHERE ra.tournament_id=? GROUP BY p.id ORDER BY total DESC,best_position ASC`).all(t.id) as any[];
  const parts=db.prepare('SELECT p.name FROM tournament_players tp JOIN players p ON p.id=tp.player_id WHERE tp.tournament_id=? ORDER BY p.name').all(t.id) as any[];
  const standings=rows.length?rows.map((r,n)=>`${n+1}. **${r.name}** — **${r.total} pts** • ${r.races} races • Best P${r.best_position??'-'} • Avg P${Number(r.avg_position||0).toFixed(1)}`).join('\n'):'No race results recorded.';
  const pList=parts.length?parts.map(r=>`• ${r.name}`).join('\n'):'No participants.';
  await i.reply({embeds:[new EmbedBuilder().setTitle(`🏆 ${t.name}`).setDescription(clean(`🎮 **Game:** ${t.game_name||'General'}\n📌 **Status:** ${t.status}\n\n**PARTICIPANTS**\n${pList}\n\n**POINT STANDINGS**\n${standings}\n\n**FIXTURES**\n${fixtureText(t.id)}`))]});
}

async function handleCommand(i:ChatInputCommandInteraction){
  if(i.commandName==='help'){await i.reply('**TGS Game Tracker**\n\n🎮 `/game`\n🏆 `/tournament`\n🛠️ `/tournament-manage`\n👥 `/tournament-player add/remove`\n👤 `/player`\n🏁 `/race`\n⚔️ `/match-result`\n📋 `/fixtures`\n📊 `/tournaments` `/players`\n📈 `/tournament-report` `/player-report` `/player-history` `/game-report`\n🎂 `/birthday set/remove/channel/list`');return;}
  if(i.commandName==='game'){if(!isManager(i)){await i.reply({content:'❌ Manager permission required.',ephemeral:true});return;}const n=i.options.getString('name',true).trim();try{db.prepare('INSERT INTO games(name) VALUES(?)').run(n);await i.reply(`🎮 Game **${n}** created.`);}catch{await i.reply(`❌ Game **${n}** already exists.`);}return;}
  if(i.commandName==='tournament'){if(!isManager(i)){await i.reply({content:'❌ Manager permission required.',ephemeral:true});return;}const n=i.options.getString('name',true).trim(),gn=i.options.getString('game',true).trim(),p=i.options.getString('password',true),c=i.options.getString('confirm_password',true);if(p!==c){await i.reply({content:'❌ Password confirmation does not match.',ephemeral:true});return;}if(p.length<4){await i.reply({content:'❌ Password must be at least 4 characters.',ephemeral:true});return;}const g=getGame(gn);if(!g){await i.reply({content:`❌ Game **${gn}** not found. Create it first with /game.`,ephemeral:true});return;}try{const x=makePassword(p);db.prepare('INSERT INTO tournaments(name,game_id,password_hash,password_salt,status,created_by) VALUES(?,?,?,?,?,?)').run(n,g.id,x.hash,x.salt,'draft',i.user.id);await i.reply({content:`🏆 Tournament **${n}** created under 🎮 **${g.name}**.\n🔐 Password protection enabled.`,ephemeral:true});}catch{await i.reply({content:`❌ Tournament **${n}** already exists.`,ephemeral:true});}return;}
  if(i.commandName==='tournament-manage'){if(!isManager(i)){await i.reply({content:'❌ Manager permission required.',ephemeral:true});return;}await i.reply({...managerPanel(),ephemeral:true});return;}
  if(i.commandName==='tournament-player'){if(!isManager(i)){await i.reply({content:'❌ Manager permission required.',ephemeral:true});return;}const sub=i.options.getSubcommand(),t=getTournament(i.options.getString('tournament',true));if(!t){await i.reply('❌ Tournament not found.');return;}const name=i.options.getString('player',true).trim();if(sub==='add'){const u=i.options.getUser('discord');const p=ensurePlayer(name,u?.id);addParticipant(t.id,p.id);await i.reply(`✅ **${p.name}** added to **${t.name}**.`);return;}const p=getPlayer(name);if(!p){await i.reply('❌ Player not found.');return;}const r=db.prepare('DELETE FROM tournament_players WHERE tournament_id=? AND player_id=?').run(t.id,p.id);await i.reply(r.changes?`✅ **${p.name}** removed from **${t.name}**.`:'❌ Player is not registered in this tournament.');return;}
  if(i.commandName==='player'){if(!isManager(i)){await i.reply({content:'❌ Manager permission required.',ephemeral:true});return;}const n=i.options.getString('name',true),u=i.options.getUser('discord');try{const p=ensurePlayer(n,u?.id);await i.reply(`👤 Player **${p.name}** registered${u?` and linked to ${u}.`:'.'}`);}catch(e:any){await i.reply(`❌ ${e?.message||'Could not register player.'}`);}return;}
  if(i.commandName==='race'){if(!isManager(i)){await i.reply({content:'❌ Manager permission required.',ephemeral:true});return;}const t=getTournament(i.options.getString('tournament',true));if(!t){await i.reply('❌ Tournament not found.');return;}const number=i.options.getInteger('number',true),track=i.options.getString('track',true).trim(),parsed=parseResults(i.options.getString('results',true));if(!parsed){await i.reply('❌ Invalid results. Use `Player1=25,Player2=18`.');return;}try{const tx=db.transaction(()=>{const race=db.prepare('INSERT INTO races(tournament_id,race_no,track) VALUES(?,?,?)').run(t.id,number,track);for(const e of parsed){const p=ensurePlayer(e.name);addParticipant(t.id,p.id);db.prepare('INSERT INTO results(race_id,player_id,points,position) VALUES(?,?,?,?)').run(race.lastInsertRowid,p.id,e.points,e.position);}});tx();await i.reply(`🏁 Race **${number}** recorded for **${t.name}**.`);}catch(e:any){await i.reply(`❌ Could not record race: ${e?.message||'unknown error'}`);}return;}
  if(i.commandName==='match-result'){if(!isManager(i)){await i.reply({content:'❌ Manager permission required.',ephemeral:true});return;}const t=getTournament(i.options.getString('tournament',true));if(!t){await i.reply('❌ Tournament not found.');return;}const round=i.options.getInteger('round',true),match=i.options.getInteger('match',true),winnerName=i.options.getString('winner',true),score1=i.options.getNumber('score1',true),score2=i.options.getNumber('score2',true);const m=db.prepare(`SELECT * FROM matches WHERE tournament_id=? AND round_no=? AND match_no=?`).get(t.id,round,match) as any;if(!m){await i.reply('❌ Fixture not found.');return;}if(m.status!=='pending'){await i.reply('❌ This fixture is already resolved.');return;}const winner=getPlayer(winnerName);if(!winner||![m.player1_id,m.player2_id].includes(winner.id)){await i.reply('❌ Winner must be one of the two fixture players.');return;}if(score1===score2){await i.reply('❌ Scores cannot be tied for a single-winner fixture.');return;}const expectedWinner=score1>score2?m.player1_id:m.player2_id;if(winner.id!==expectedWinner){await i.reply('❌ Winner does not match the higher score.');return;}db.prepare("UPDATE matches SET winner_id=?,score1=?,score2=?,status='completed',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(winner.id,score1,score2,m.id);const advanced=autoAdvanceRound(t.id,round);await i.reply(`✅ Match **R${round} M${match}** recorded. Winner: **${winner.name}**.${advanced?.final?' 🏆 Tournament completed!':''}`);return;}
  if(i.commandName==='fixtures'){const t=getTournament(i.options.getString('tournament',true));if(!t){await i.reply('❌ Tournament not found.');return;}await i.reply({embeds:[new EmbedBuilder().setTitle(`📋 ${t.name} Fixtures`).setDescription(clean(fixtureText(t.id)))]});return;}
  if(i.commandName==='tournaments'){const game=i.options.getString('game');const rows=game?db.prepare('SELECT t.name,g.name game_name,t.status FROM tournaments t JOIN games g ON g.id=t.game_id WHERE g.name=? COLLATE NOCASE ORDER BY t.created_at DESC').all(game) as any[]:db.prepare('SELECT t.name,g.name game_name,t.status FROM tournaments t LEFT JOIN games g ON g.id=t.game_id ORDER BY t.created_at DESC').all() as any[];await i.reply({embeds:[new EmbedBuilder().setTitle(game?`🏆 ${game} Tournaments`:'🏆 All Tournaments').setDescription(clean(rows.length?rows.map((r,n)=>`${n+1}. **${r.name}** — 🎮 ${r.game_name||'General'} • ${r.status}`).join('\n'):'No tournaments found.'))]});return;}
  if(i.commandName==='players'){const rows=db.prepare('SELECT p.name,COUNT(DISTINCT r.id) races,COALESCE(SUM(r.points),0) points FROM players p LEFT JOIN results r ON r.player_id=p.id GROUP BY p.id ORDER BY points DESC,p.name').all() as any[];await i.reply({embeds:[new EmbedBuilder().setTitle('👥 TGS Players').setDescription(clean(rows.length?rows.map((r,n)=>`${n+1}. **${r.name}** — ${r.points} pts • ${r.races} races`).join('\n'):'No players found.'))]});return;}
  if(i.commandName==='tournament-report'){await tournamentReport(i,i.options.getString('tournament',true));return;}
  if(i.commandName==='player-report'||i.commandName==='player-history'){const p=getPlayer(i.options.getString('player',true));if(!p){await i.reply('❌ Player not found.');return;}const game=i.options.getString('game');const rows=db.prepare(`SELECT t.name tournament,g.name game_name,ra.race_no,ra.track,r.points,r.position FROM results r JOIN races ra ON ra.id=r.race_id JOIN tournaments t ON t.id=ra.tournament_id LEFT JOIN games g ON g.id=t.game_id WHERE r.player_id=? ${game?'AND g.name=? COLLATE NOCASE':''} ORDER BY ra.created_at DESC,ra.race_no DESC`).all(...(game?[p.id,game]:[p.id])) as any[];if(i.commandName==='player-history'){await i.reply({embeds:[new EmbedBuilder().setTitle(`📋 ${p.name} History`).setDescription(clean(rows.length?rows.map(r=>`🎮 **${r.game_name||'General'}** • **${r.tournament}** • Race ${r.race_no} • ${r.track} — **P${r.position??'-'} / ${r.points} pts**`).join('\n'):'No races recorded.'))]});return;}const total=rows.reduce((s,r)=>s+Number(r.points),0),tournaments=new Set(rows.map(r=>r.tournament)).size,wins=rows.filter(r=>Number(r.position)===1).length;await i.reply({embeds:[new EmbedBuilder().setTitle(`📊 ${p.name} Report`).setDescription(clean(`**Total Points:** ${total}\n**Tournaments:** ${tournaments}\n**Races:** ${rows.length}\n**Wins (P1):** ${wins}\n\n${rows.length?rows.map(r=>`🎮 **${r.game_name||'General'}** • ${r.tournament} • Race ${r.race_no} — **P${r.position??'-'}**, ${r.points} pts`).join('\n'):'No records found.'}`))]});return;}
  if(i.commandName==='game-report'){const g=getGame(i.options.getString('game',true));if(!g){await i.reply('❌ Game not found.');return;}const ts=db.prepare('SELECT t.name,COUNT(DISTINCT ra.id) races FROM tournaments t LEFT JOIN races ra ON ra.tournament_id=t.id WHERE t.game_id=? GROUP BY t.id ORDER BY t.created_at DESC').all(g.id) as any[];const ps=db.prepare('SELECT p.name,SUM(r.points) points,COUNT(r.id) races FROM results r JOIN players p ON p.id=r.player_id JOIN races ra ON ra.id=r.race_id JOIN tournaments t ON t.id=ra.tournament_id WHERE t.game_id=? GROUP BY p.id ORDER BY points DESC').all(g.id) as any[];await i.reply({embeds:[new EmbedBuilder().setTitle(`🎮 ${g.name} Report`).setDescription(clean(`**Tournaments**\n${ts.length?ts.map((r,n)=>`${n+1}. **${r.name}** — ${r.races} races`).join('\n'):'None'}\n\n**Players**\n${ps.length?ps.map((r,n)=>`${n+1}. **${r.name}** — ${r.points} pts • ${r.races} races`).join('\n'):'None'}`))]});return;}
  if(i.commandName==='birthday'){
    const sub=i.options.getSubcommand();
    if(!isManager(i)){await i.reply({content:'❌ Manager permission required.',ephemeral:true});return;}
    if(sub==='set'){const u=i.options.getUser('user',true),month=i.options.getInteger('month',true),day=i.options.getInteger('day',true);const valid=new Date(2000,month-1,day).getMonth()===month-1&&new Date(2000,month-1,day).getDate()===day;if(!valid){await i.reply({content:'❌ Invalid month/day combination.',ephemeral:true});return;}db.prepare('INSERT INTO birthdays(discord_id,month,day,enabled,updated_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(discord_id) DO UPDATE SET month=excluded.month,day=excluded.day,enabled=1,updated_at=CURRENT_TIMESTAMP').run(u.id,month,day,1);await i.reply({content:`🎂 Birthday saved for ${u}: **${String(day).padStart(2,'0')}/${String(month).padStart(2,'0')}**.`,ephemeral:true});return;}
    if(sub==='remove'){const u=i.options.getUser('user',true);db.prepare('DELETE FROM birthdays WHERE discord_id=?').run(u.id);await i.reply({content:`🗑️ Birthday removed for ${u}.`,ephemeral:true});return;}
    if(sub==='channel'){const ch=i.options.getChannel('channel',true);db.prepare('INSERT INTO birthday_config(guild_id,channel_id,enabled,updated_at) VALUES(?,?,1,CURRENT_TIMESTAMP) ON CONFLICT(guild_id) DO UPDATE SET channel_id=excluded.channel_id,enabled=1,updated_at=CURRENT_TIMESTAMP').run(guildId,ch.id);await i.reply({content:`🎂 Birthday announcements will be sent in ${ch}.`,ephemeral:true});return;}
    const rows=db.prepare('SELECT discord_id,month,day FROM birthdays WHERE enabled=1 ORDER BY month,day').all() as any[];await i.reply({content:rows.length?rows.map(r=>`<@${r.discord_id}> — ${String(r.day).padStart(2,'0')}/${String(r.month).padStart(2,'0')}`).join('\n'):'No birthdays configured.',ephemeral:true});return;
  }
}

function updateModal(t:any){const m=new ModalBuilder().setCustomId(`tgs:update-form:${t.id}`).setTitle('Update Tournament');m.addComponents(
  new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('password').setLabel('Tournament password').setStyle(TextInputStyle.Short).setRequired(true).setMinLength(4)),
  new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('name').setLabel('Tournament name').setStyle(TextInputStyle.Short).setRequired(true).setValue(t.name)),
  new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('game').setLabel('Game name').setStyle(TextInputStyle.Short).setRequired(true).setValue(t.game_name||'General')),
  new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId('status').setLabel('Status: draft/live/completed').setStyle(TextInputStyle.Short).setRequired(true).setValue(t.status)),
);return m;}

async function handleSelect(i:StringSelectMenuInteraction){if(i.customId!=='tgs:tournament-select')return;const id=Number(i.values[0]),t=getTournamentById(id);if(!t){await i.update({content:'❌ Tournament not found.',components:[]});return;}await i.update({content:`🏆 **${t.name}**\n🎮 **${t.game_name||'General'}**\n📌 **${t.status}**\n\nChoose an action:`,components:[managerButtons(id)]});}

async function handleButton(i:ButtonInteraction){const [prefix,action,idText]=i.customId.split(':');if(prefix!=='tgs')return;if(!isManager(i as any)){await i.reply({content:'❌ Manager permission required.',ephemeral:true});return;}const id=Number(idText),t=getTournamentById(id);if(!t){await i.reply({content:'❌ Tournament not found.',ephemeral:true});return;}if(action==='report'){await tournamentReport(i,t.name);return;}if(action==='update'){await i.showModal(updateModal(t));return;}if(action==='delete'||action==='fixtures'){await i.showModal(passwordModal(action,id));return;}}

async function handlePasswordModal(i:ModalSubmitInteraction){const parts=i.customId.split(':');const action=parts[2],id=Number(parts[3]);const t=await passwordOk(i,id);if(!t)return;
  if(action==='delete'){db.prepare('DELETE FROM tournaments WHERE id=?').run(id);await i.reply({content:`🗑️ Tournament **${t.name}** deleted.`,ephemeral:true});return;}
  if(action==='fixtures'){try{const r=createFixtures(id);await i.reply({content:`✅ Fixtures created for **${t.name}**.\n👥 Players: ${r.players}\n📐 Bracket size: ${r.size}\n\nUse \/fixtures to view them.`,ephemeral:true});}catch(e:any){await i.reply({content:`❌ ${e?.message||'Could not create fixtures.'}`,ephemeral:true});}return;}
}

async function handleUpdateForm(i:ModalSubmitInteraction){const id=Number(i.customId.split(':')[2]),t=getTournamentById(id);if(!t){await i.reply({content:'❌ Tournament not found.',ephemeral:true});return;}const p=i.fields.getTextInputValue('password');if(!t.password_hash||!t.password_salt||!verifyPassword(p,t.password_hash,t.password_salt)){await i.reply({content:'❌ Incorrect tournament password.',ephemeral:true});return;}const name=i.fields.getTextInputValue('name').trim(),gameName=i.fields.getTextInputValue('game').trim(),status=i.fields.getTextInputValue('status').trim().toLowerCase();if(!name){await i.reply({content:'❌ Tournament name cannot be empty.',ephemeral:true});return;}const g=getGame(gameName);if(!g){await i.reply({content:`❌ Game **${gameName}** not found.`,ephemeral:true});return;}if(!['draft','live','completed','fixtures_created'].includes(status)){await i.reply({content:'❌ Invalid status.',ephemeral:true});return;}try{db.prepare('UPDATE tournaments SET name=?,game_id=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(name,g.id,status,id);await i.reply({content:`✅ Tournament updated to **${name}** • 🎮 ${g.name} • ${status}`,ephemeral:true});}catch{await i.reply({content:'❌ Could not update tournament. The name may already exist.',ephemeral:true});}}

function birthdayDateIndia(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Kolkata',year:'numeric',month:'numeric',day:'numeric'}).formatToParts(new Date());const get=(type:string)=>Number(parts.find(p=>p.type===type)?.value);return{year:get('year'),month:get('month'),day:get('day')};}
async function checkBirthdays(){try{const d=birthdayDateIndia();const configs=db.prepare('SELECT guild_id,channel_id FROM birthday_config WHERE enabled=1 AND channel_id IS NOT NULL').all() as any[];for(const cfg of configs){const rows=db.prepare('SELECT discord_id FROM birthdays WHERE enabled=1 AND month=? AND day=?').all(d.month,d.day) as any[];for(const row of rows){const already=db.prepare('SELECT 1 FROM birthday_announcements WHERE guild_id=? AND discord_id=? AND year=?').get(cfg.guild_id,row.discord_id,d.year);if(already)continue;const guild=client.guilds.cache.get(cfg.guild_id);if(!guild)continue;const channel=guild.channels.cache.get(cfg.channel_id);if(!channel||channel.type!==ChannelType.GuildText)continue;await channel.send(`🎂🎉 Happy Birthday <@${row.discord_id}>!\nWishing you a fantastic birthday from **TGS Gaming**! 🥳🎈`);db.prepare('INSERT INTO birthday_announcements(guild_id,discord_id,year) VALUES(?,?,?)').run(cfg.guild_id,row.discord_id,d.year);}}}catch(e){console.error('Birthday check failed:',e);}}

client.once('ready',async c=>{console.log(`Logged in as ${c.user.tag}`);try{await registerCommands();}catch(e){console.error('Command registration failed:',e);}await checkBirthdays();setInterval(checkBirthdays,10*60*1000);});
client.on('interactionCreate',async(i:Interaction)=>{try{if(i.isAutocomplete()){if(i.commandName==='tournament'){const focused=i.options.getFocused(true);if(focused.name==='game'){const query=String(focused.value??'').trim();const games=db.prepare("SELECT name FROM games WHERE name LIKE ? COLLATE NOCASE ORDER BY name ASC LIMIT 25").all(`%${query}%`) as {name:string}[];await i.respond(games.map(g=>({name:g.name,value:g.name})));return;}}if(i.commandName==='fixtures'){const focused=i.options.getFocused(true);if(focused.name==='tournament'){const query=String(focused.value??'').trim();const tournaments=db.prepare("SELECT t.id,t.name,g.name game_name,t.status FROM tournaments t LEFT JOIN games g ON g.id=t.game_id WHERE t.name LIKE ? COLLATE NOCASE ORDER BY t.created_at DESC LIMIT 25").all(`%${query}%`) as {id:number,name:string,game_name:string|null,status:string}[];await i.respond(tournaments.map(t=>({name:`${t.name} • ${t.game_name||'General'} • ${t.status}`.slice(0,100),value:t.name})));return;}}return;}if(i.isChatInputCommand())await handleCommand(i);else if(i.isStringSelectMenu())await handleSelect(i);else if(i.isButton())await handleButton(i);else if(i.isModalSubmit()&&i.customId.startsWith('tgs:password:'))await handlePasswordModal(i);else if(i.isModalSubmit()&&i.customId.startsWith('tgs:update-form:'))await handleUpdateForm(i);}catch(e:any){console.error('Interaction error:',e);const msg='❌ Something went wrong while processing this action.';if(i.isRepliable()){if(i.replied||i.deferred)await i.followUp({content:msg,ephemeral:true}).catch(()=>{});else await i.reply({content:msg,ephemeral:true}).catch(()=>{});}}});
client.login(token);
